-- ==========================================================================
-- FIMBLOGS SUPABASE DATABASE SCHEMA SETUP
-- Run this script in your Supabase Dashboard -> SQL Editor
-- ==========================================================================

-- 1. Create Articles Table
CREATE TABLE IF NOT EXISTS public.articles (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Daily Insights',
  read_time TEXT DEFAULT '3 min read',
  date TEXT NOT NULL,
  views INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT,
  image TEXT,
  excerpt TEXT,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Subscribers Table
CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscribers ENABLE ROW LEVEL SECURITY;

-- 4. Create Public Read & Write Policies for Articles (Allows readers & CMS admin to manage articles)
CREATE POLICY "Public Read Articles" ON public.articles FOR SELECT USING (true);
CREATE POLICY "Public Insert Articles" ON public.articles FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Articles" ON public.articles FOR UPDATE USING (true);
CREATE POLICY "Public Delete Articles" ON public.articles FOR DELETE USING (true);

-- 5. Create Public Policies for Subscribers
CREATE POLICY "Public Read Subscribers" ON public.subscribers FOR SELECT USING (true);
CREATE POLICY "Public Insert Subscribers" ON public.subscribers FOR INSERT WITH CHECK (true);
