-- ==========================================================================
-- FIMBLOGS SUPABASE DATABASE SCHEMA SETUP
-- Run this script in your Supabase Dashboard -> SQL Editor
-- ==========================================================================

-- 1. Create Articles Table
CREATE TABLE IF NOT EXISTS public.articles (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Daily Insights',
  read_time TEXT DEFAULT '3 min read',
  date TEXT NOT NULL,
  views INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT,
  image TEXT,
  excerpt TEXT,
  content TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create Subscribers Table
CREATE TABLE IF NOT EXISTS public.subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Create Quizzes Table
CREATE TABLE IF NOT EXISTS public.quizzes (
  id TEXT PRIMARY KEY,
  article_id TEXT REFERENCES public.articles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  pass_percentage INTEGER DEFAULT 60,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Create Quiz Questions Table (MCQ)
CREATE TABLE IF NOT EXISTS public.quiz_questions (
  id TEXT PRIMARY KEY,
  quiz_id TEXT REFERENCES public.quizzes(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option TEXT NOT NULL, -- 'A', 'B', 'C', or 'D'
  explanation TEXT,
  question_order INTEGER DEFAULT 1
);

-- 8. Create Quiz Attempts / Scoring Table
CREATE TABLE IF NOT EXISTS public.quiz_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id TEXT REFERENCES public.quizzes(id) ON DELETE CASCADE,
  user_name TEXT DEFAULT 'Tamil Reader',
  score INTEGER NOT NULL,
  total_questions INTEGER NOT NULL,
  percentage INTEGER NOT NULL,
  passed BOOLEAN NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Enable RLS & Create Policies for Quizzes, Questions, Attempts
ALTER TABLE public.quizzes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Read Quizzes" ON public.quizzes FOR SELECT USING (true);
CREATE POLICY "Public Insert Quizzes" ON public.quizzes FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Quizzes" ON public.quizzes FOR UPDATE USING (true);
CREATE POLICY "Public Delete Quizzes" ON public.quizzes FOR DELETE USING (true);

CREATE POLICY "Public Read Questions" ON public.quiz_questions FOR SELECT USING (true);
CREATE POLICY "Public Insert Questions" ON public.quiz_questions FOR INSERT WITH CHECK (true);
CREATE POLICY "Public Update Questions" ON public.quiz_questions FOR UPDATE USING (true);
CREATE POLICY "Public Delete Questions" ON public.quiz_questions FOR DELETE USING (true);

CREATE POLICY "Public Read Attempts" ON public.quiz_attempts FOR SELECT USING (true);
CREATE POLICY "Public Insert Attempts" ON public.quiz_attempts FOR INSERT WITH CHECK (true);

